package hexlet;/*
 * This Java source file was generated by the Gradle 'init' task.
 */

import com.fasterxml.jackson.core.JsonProcessingException;

import hexlet.code.Differ;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import java.io.File;
import java.util.TreeMap;

import static org.junit.jupiter.api.Assertions.*;
import static org.assertj.core.api.Assertions.assertThat;


class AppTest {
    public static TreeMap<String, Object> map1;
    public static TreeMap<String, Object> map2;

    @BeforeAll
    public static void a() {
        map1 = new TreeMap<>();
        map2 = new TreeMap<>();
    }

    @Test
    @DisplayName("formatter work testing: ")
    public void formatterTest() throws JsonProcessingException {

        TreeMap<String, Object> map1 = new TreeMap<>();
        TreeMap<String, Object> map2 = new TreeMap<>();

        File file1 = new File("File1.json");
        File file2 = new File("File2.json");


        String incorrectFormat = "format1";
        String result = "Incorrect format!";

        assertEquals(Differ.generate(file1, file2, incorrectFormat), result);
    }
}
