/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package hexlet.code;

import picocli.CommandLine;
import java.io.IOException;
import java.nio.file.Path;
import java.util.concurrent.Callable;

@CommandLine.Command(name = "gendiff", mixinStandardHelpOptions = true,
        description = "Compares two configuration files and shows a difference.")

public final class App implements Callable {

    @CommandLine.Option(names = {"-f", "--format"},  required = true, description = "output format [default: stylish]",
            defaultValue = "stylish")
    private String format1;
    @CommandLine.Parameters(paramLabel = "filepath1",
            defaultValue = "./src/main/resources/ExampleFile1.json", description = "path to first file")
    private Path path1;
    @CommandLine.Parameters(paramLabel = "filepath2",
            defaultValue = "./src/main/resources/ExampleFile2.json", description = "path to second file")
    private Path path2;

    public static void main(String[] args) throws IOException {
        new CommandLine(new App()).execute(args);
    }

    @Override
    public Object call() {

        String pathOfFile1 = path1.toAbsolutePath().normalize().toString();
        String pathOfFile2 = path2.toAbsolutePath().normalize().toString();

        try {
            String result = Differ.generate(pathOfFile1, pathOfFile2, format1);
            System.out.println(result);
            return result;
        } catch (IOException e) {
            System.out.println(e.getMessage());
            return e.getMessage();
        }
    }
}
